### ISSUE TITLE
after call picked by receiver call not connecting to camera , Showing the outgoing call screen

### ISSUE THREAD

**Issue by subhashDev11** [ReberSincar/Flutter-WebRTC-Socketio-Video-Call#1]

**Comment by ReberSincar** [comment]
Hello, It may be on some devices. Change caller and receiver phones. When i call from my phone call is not start but when i call another phone call is start. I think some phones prevent the p2p connection. I used only google stun servers. For stable call connection we need to setup a turn server.

**Comment by inprise1980** [comment]
I have set up a turn server, but I cannot connect to it on different networks

**Comment by inprise1980** [comment]
@ReberSincar
